package co.edu.usbcali.banco.modelo;
// Generated 30/01/2018 10:10:31 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Positive;
import javax.validation.constraints.Size;

/**
 * TipoUsuario generated by hbm2java
 */
@Entity
@Table(name = "tipo_usuario", schema = "public")
public class TipoUsuario implements java.io.Serializable {
	
	@NotNull(message="El id no puede ser nulo")
	private long tiusId;
	
	@NotNull
	@Size(min=3, max=20)
	@NotEmpty
	private String nombre;
	
	private char activo;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public TipoUsuario() {
	}

	public TipoUsuario(long tiusId, String nombre, char activo) {
		this.tiusId = tiusId;
		this.nombre = nombre;
		this.activo = activo;
	}

	public TipoUsuario(long tiusId, String nombre, char activo, Set<Usuario> usuarios) {
		this.tiusId = tiusId;
		this.nombre = nombre;
		this.activo = activo;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "tius_id", unique = true, nullable = false)
	public long getTiusId() {
		return this.tiusId;
	}

	public void setTiusId(long tiusId) {
		this.tiusId = tiusId;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "activo", nullable = false, length = 1)
	public char getActivo() {
		return this.activo;
	}

	public void setActivo(char activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoUsuario")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
